spring.application.name=gateway

# Remove after https://github.com/spring-cloud/spring-cloud-gateway/pull/4250 is released.
logging.level.org.hibernate.validator.internal.metadata.aggregated.CascadingMetaDataBuilder=ERROR
